include Makefile_setup

NAME_CLIENT			= client
CLIENT_SOURCES		= $(addprefix $(PATH_SOURCES)/, $(FILE_CLIENT_SOURCES))
FILE_CLIENT_OBJECTS	= $(CLIENT_SOURCES:$(PATH_SOURCES)/%.c=$(PATH_OBJECTS)/%.o)

NAME_SERVER			= server
SERVER_SOURCES		= $(addprefix $(PATH_SOURCES)/, $(FILE_SERVER_SOURCES))
FILE_SERVER_OBJECTS	= $(SERVER_SOURCES:$(PATH_SOURCES)/%.c=$(PATH_OBJECTS)/%.o)

FILE_HEADER			= $(PATH_INCLUDES)/minitalk.h

FILE_CLIENT_SOURCES	= client.c
FILE_SERVER_SOURCES	= server.c

all: $(NAME_CLIENT) $(NAME_SERVER)

$(NAME_CLIENT): $(LIBFT) $(PATH_OBJECTS) $(FILE_CLIENT_OBJECTS) $(FILE_HEADER)
	$(LINKER) $(FLAG_C) $(FILE_CLIENT_OBJECTS) $(LIBFT) -o $@

$(NAME_SERVER): $(LIBFT) $(PATH_OBJECTS) $(FILE_SERVER_OBJECTS) $(FILE_HEADER)
	$(LINKER) $(FLAG_C) $(FILE_SERVER_OBJECTS) $(LIBFT) -o $@

$(LIBFT):
	@$(MAKE) -C $(PATH_LIBFT) all

$(PATH_OBJECTS)/%.o: $(PATH_SOURCES)/%.c $(FILE_HEADER)
	$(COMPILER) $(FLAG_C) $(INCLUDES) $< -o $@

$(PATH_OBJECTS):
	$(MAKE_DIR) $(PATH_OBJECTS)

clean:
	$(REMOVE_FORCE) $(PATH_OBJECTS)
	@$(MAKE) -C $(PATH_LIBFT) clean

fclean: clean
	$(REMOVE_FORCE) $(NAME_CLIENT) $(NAME_SERVER)
	@$(MAKE) -C $(PATH_LIBFT) fclean

re: fclean all

.PHONY: all fclean clean re run leak test debug
